[env:esp32-s3-devkitc-1]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^7.1.0
    claws/BH1750@^1.2.0
    h2zero/NimBLE-Arduino@^1.4.0
build_flags = 
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_MISO=-1
    -DTFT_CS=10
    -DTFT_DC=8
    -DTFT_RST=9
    # -DTFT_BL=7  # No BL pin on this module
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DLOAD_GLCD=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
    -DCORE_DEBUG_LEVEL=3
    -DUSE_HSPI_PORT=1
